[project]
name = "django_backend"
version = "0.0.1"
description = ""
readme = "README.md"
requires-python = ">=3.13.9"
dependencies = [
    "pip>=25.2",
    "django>=5.2.7",
    "psycopg2-binary>=2.9.11",
    "pillow>=12.0.0",
    "python-dotenv>=1.1.1",
]
